name = "castromonjeasociados"
account_id = "8a155f458b4232b4c143523e07f81729"
compatibility_date = "2026-08-01"
main = "./src/worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"